LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
 
LOCAL_SRC_FILES := cpuusage.c
 
LOCAL_SHARED_LIBRARIES := libcutils
LOCAL_CFLAGS := -DANDROID_COMPATIBLE -Wall
 
LOCAL_MODULE := cpu-daemon

#LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT_SBIN)
LOCAL_MODULE_TAGS := debug

LOCAL_CFLAGS += -DCPU_FREQ
LOCAL_CFLAGS += -DCPU_THREAD

LOCAL_CFLAGS += -DPROC_MEM
LOCAL_C_INCLUDES := $(call include-path-for, libpagemap)
LOCAL_SHARED_LIBRARIES += libpagemap

include $(BUILD_EXECUTABLE)
